version: "2"

services:
  database:
    build: .
    volumes:
      - ".:/code"
    network_mode: host
    command: npm run dev
    environment:
      - CQ_HOST=${CQ_HOST}
      - CQ_ACCESS_TOKEN=${CQ_ACCESS_TOKEN}
      - TSBOT_ADMIN=${TSBOT_ADMIN}
      - QQAI_APPID=${QQAI_APPID}
      - QQAI_APPKEY=${QQAI_APPKEY}
      - BOT_DEBUG=true
      - PRIVA_HOST=${PRIVA_HOST}
      - DISABLE_SHARE=${DISABLE_SHARE}
